CREATE DATABASE `mappy` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE `mappy`.`mappy` (
`id` INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`name` VARCHAR( 255 ) NOT NULL DEFAULT '',
`country` VARCHAR( 255 ) NOT NULL DEFAULT '',
`region` VARCHAR( 255 ) NOT NULL DEFAULT '',
`ville` VARCHAR( 255 ) NOT NULL DEFAULT '',
`x` FLOAT( 20, 17 ) NOT NULL DEFAULT '0',
`y` FLOAT( 20, 17 ) NOT NULL DEFAULT '0'
) ENGINE = MYISAM ;