<?php echo Controller::dispatch('Admin_Header', array(__('Inmuebles'), $this->codigo, __('Editar'), __($this->idioma))); ?>

<div id="breadcrumb">
  <ul>
    <li><a href="<?php echo new Url('/admin/inmuebles'); ?>"><?php echo __('Inmuebles'); ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->codigo"); ?>"><?php echo $this->codigo; ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->codigo/editar"); ?>"><?php echo __('Editar'); ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->codigo/editar/$this->idioma"); ?>"><?php echo __($this->idioma); ?></a></li>
  </ul>
  <div class="clear"><!-- --></div>
</div>

<div id="content">
<?php if ( !( $this->inmueble->found() ) ) : ?>
  <div class="error">
    <p><?php echo __('Registro <strong>$0</strong> no encontrado.', $this->codigo); ?></p>
  </div>
<?php else : ?>
<?php if ( $this->errors ) : ?>
  <div class="error">
    <p><?php echo __('Por favor verifique los siguientes errores:'); ?></p>
    <ul>
<?php if ( $this->errors['nombre'] ) : ?>
      <li><?php echo __('Nombre requerido.'); ?></li>
<?php endif; ?>
<?php if ( $this->errors['titulo'] ) : ?>
      <li><?php echo __('Título requerido.'); ?></li>
<?php endif; ?>
<?php if ( isset($this->errors['url']) && $this->errors['url'] ) : ?>
      <li><?php echo __('URL requerida.'); ?></li>
<?php endif; ?>
<?php if ( $this->errors['descripcion'] ) : ?>
      <li><?php echo __('Descripción requerida.'); ?></li>
<?php endif; ?>
    </ul>
  </div>
<?php endif; ?>
<?php if ( !( $this->contenido->found() ) ) : ?>
  <div class="info">
    <p><?php echo __('No se encontraron datos en <strong>$0</strong>. Elija la URL, esta no puede ser editada en el futuro porque se perdería la indexación de buscadores. Puede utilizar letras, números y puntos únicamente.', __($this->idioma)); ?></p>
    <p><?php echo __('Recuerde que lo que ingrese aquí tiene el mayor peso al posicionarse. Puede ingresar una frase separada por puntos (Ej: <em>mi.santa.tu.hogar.en.colonia</em>) para posicionar ciertas palabras claves. Personalice al máximo y utilice únicamente palabras en el idioma.'); ?></p>
  </div>
<?php endif; ?>
  <form action="<?php echo new Url(); ?>" method="post">
    <dl>
      <dt>
        <label for="nombre"><?php echo __('Nombre'); ?></label>
        <span class="required">*</span>
      </dt>
      <dd>
        <input type="text" name="nombre" id="nombre" value="<?php echo $this->nombre; ?>" />
      </dd>

      <dt>
        <label for="titulo"><?php echo __('Título'); ?></label>
        <span class="required">*</span>
      </dt>
      <dd>
        <input type="text" name="titulo" id="titulo" value="<?php echo $this->titulo; ?>" />
        <p><?php echo __('Aparecerá en la cabecera del navegador.'); ?></p>
      </dd>

<?php if ( $this->contenido->found() ) : ?>
      <dt><?php echo __('URL'); ?></dt>
      <dd>
        <span class="path">/<?php echo $this->idioma; ?>/</span>
        <span><?php echo $this->contenido->url; ?></span>
        <p><?php echo __('La URL no puede ser editada.'); ?></p>
      </dd>
<?php else : ?>
      <dt>
        <label for="url"><?php echo __('URL'); ?></label>
        <span class="required">*</span>
      </dt>
      <dd>
        <span class="path">/<?php echo $this->idioma; ?>/</span>
        <input type="text" name="url" id="url" value="<?php echo $this->url; ?>" />
      </dd>
<?php endif; ?>

      <dt>
        <label for="descripcion"><?php echo __('Descripción'); ?></label>
        <span class="required">*</span>
        <p><?php echo __('El código <a href="$0">Wiki</a> se encuentra habilitado. No se permite código <abbr title="HyperText Markup Language">HTML</abbr>.', new Url('/admin/ayuda/wiki')); ?></p>
      </dt>
      <dd>
        <textarea name="descripcion" id="descripcion" class="html" rows="3" cols="18"><?php echo $this->descripcion; ?></textarea>
      </dd>

      <dl>
        <dd class="submit">
          <input type="submit" value="<?php echo __('Guardar'); ?>" />
          <span><?php echo __('ó <a href="$0">Cancelar</a>', new Url("/admin/inmuebles/$this->codigo/editar")); ?></span>
        </dd>
      </dl>
    </dl>
  </form>
<?php endif; ?>
</div>

<?php echo Controller::dispatch('Admin_Footer'); ?>