<?php echo Controller::dispatch('Admin_Header', array(__('Inmuebles'), $this->inmuebleCodigo, __('Páginas'), $this->paginaCodigo, __('Eliminar'))); ?>

<div id="breadcrumb">
  <ul>
    <li><a href="<?php echo new Url('/admin/inmuebles'); ?>"><?php echo __('Inmuebles'); ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->inmuebleCodigo"); ?>"><?php echo $this->inmuebleCodigo; ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->inmuebleCodigo/paginas"); ?>"><?php echo __('Páginas'); ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->inmuebleCodigo/paginas/$this->paginaCodigo"); ?>"><?php echo $this->paginaCodigo; ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->inmuebleCodigo/paginas/$this->paginaCodigo/eliminar"); ?>"><?php echo __('Eliminar'); ?></a></li>
  </ul>
  <div class="clear"><!-- --></div>
</div>

<div id="content">
<?php if ( !( $this->inmueble->found() ) ) : ?>
  <div class="error">
    <p><?php echo __('Registro <strong>$0</strong> no encontrado.', $this->inmuebleCodigo); ?></p>
  </div>
<?php elseif ( !( $this->pagina->found() ) ) : ?>
 <div class="error">
    <p><?php echo __('Registro <strong>$0</strong> no encontrado.', $this->paginaCodigo); ?></p>
  </div>
<?php else : ?>
  <div class="warning">
    <p><?php echo __('Se encuentra a punto de eliminar a <strong>$0</strong> del sistema. ¿Desea continuar?', $this->paginaCodigo); ?></p>
  </div>
  <form action="<?php echo new Url(); ?>" method="post">
    <dl>
      <dd class="submit">
        <input type="submit" value="<?php echo __('Eliminar'); ?>" />
        <span><?php echo __('ó <a href="$0">Cancelar</a>', new Url("/admin/inmuebles/$this->inmuebleCodigo/paginas/$this->paginaCodigo")); ?></span>
      </dd>
    </dl>
  </form>
<?php endif; ?>
</div>

<?php echo Controller::dispatch('Admin_Footer'); ?>