<?php echo Controller::dispatch('Admin_Header', array(__('Inmuebles'), $this->inmuebleCodigo, __('Páginas'), $this->paginaCodigo, __('Mover'))); ?>

<div id="breadcrumb">
  <ul>
    <li><a href="<?php echo new Url('/admin/inmuebles'); ?>"><?php echo __('Inmuebles'); ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->inmuebleCodigo"); ?>"><?php echo $this->inmuebleCodigo; ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->inmuebleCodigo/paginas"); ?>"><?php echo __('Páginas'); ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->inmuebleCodigo/paginas/$this->paginaCodigo"); ?>"><?php echo $this->paginaCodigo; ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->inmuebleCodigo/paginas/$this->paginaCodigo/mover"); ?>"><?php echo __('Mover'); ?></a></li>
  </ul>
  <div class="clear"><!-- --></div>
</div>

<div id="content">
<?php if ( !( $this->inmueble->found() ) ) : ?>
  <div class="error">
    <p><?php echo __('Registro <strong>$0</strong> no encontrado.', $this->inmuebleCodigo); ?></p>
  </div>
<?php elseif ( !( $this->pagina->found() ) ) : ?>
  <div class="error">
    <p><?php echo __('Registro <strong>$0</strong> no encontrado.', $this->paginaCodigo); ?></p>
  </div>
<?php else : ?>
<?php if ( $this->errors ) : ?>
  <div class="error">
    <p><?php echo __('Por favor verifique los siguientes errores:'); ?></p>
    <ul>
<?php if ( $this->errors['signo'] ) : ?>
      <li><?php echo __('Operación requerida.'); ?></li>
<?php endif; ?>
<?php if ( $this->errors['cantidad'] ) : ?>
      <li><?php echo __('Cantidad de lugares requeridos.'); ?></li>
<?php endif; ?>
    </ul>
  </div>
<?php endif; ?>
  <form action="<?php echo new Url(); ?>" method="post">
    <dl>
      <dt>
        <label for="signo"><?php echo __('Operación'); ?></label>
        <span class="required">*</span>
      </dt>
      <dd>
        <select name="signo" id="signo">
<?php if ( '-' == $this->signo ) : ?>
          <option value="-" selected="selected"><?php echo __('Subir'); ?></option>
<?php else : ?>
          <option value="-"><?php echo __('Subir'); ?></option>
<?php endif; ?>
<?php if ( '+' == $this->signo ) : ?>
          <option value="+" selected="selected"><?php echo __('Bajar'); ?></option>
<?php else : ?>
          <option value="+"><?php echo __('Bajar'); ?></option>
<?php endif; ?>
        </select>
      </dd>

      <dt>
        <label for="cantidad"><?php echo __('Lugares'); ?></label>
        <span class="required">*</span>
      </dt>
      <dd>
        <input type="text" class="number" name="cantidad" id="cantidad" value="<?php echo $this->cantidad; ?>" />
      </dd>

      <dd class="submit">
        <input type="submit" value="<?php echo __('Mover'); ?>" />
        <span><?php echo __('ó <a href="$0">Cancelar</a>', new Url("/admin/inmuebles/$this->inmuebleCodigo/paginas/$this->paginaCodigo")); ?></span>
      </dd>
    </dl>
  </form>
<?php endif; ?>
</div>

<?php echo Controller::dispatch('Admin_Footer'); ?>