<?php echo Controller::dispatch('Admin_Header', array(__('Inmuebles'), $this->codigo, __('Activo'))); ?>

<div id="breadcrumb">
  <ul>
    <li><a href="<?php echo new Url('/admin/inmuebles'); ?>"><?php echo __('Inmuebles'); ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->codigo"); ?>"><?php echo $this->codigo; ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->codigo/activo"); ?>"><?php echo __('Activo'); ?></a></li>
  </ul>
  <div class="clear"><!-- --></div>
</div>

<div id="content">
<?php if ( !( $this->inmueble->found() ) ) : ?>
  <div class="error">
    <p><?php echo __('Registro <strong>$0</strong> no encontrado.', $this->codigo); ?></p>
  </div>
<?php else : ?>
  <form action="<?php echo new Url(); ?>" method="post">
<?php if ( $this->inmueble->activo == 1 ) : ?>
    <p><?php echo __('El inmueble <strong>$0</strong> se encuentra visible. ¿Deséa ocultarlo?', $this->codigo); ?></p>
<?php else : ?>
    <p><?php echo __('El inmueble <strong>$0</strong> se encuentra oculto. ¿Deséa mostrarlo?', $this->codigo); ?></p>
<?php endif; ?>
    <dl>
      <dd class="submit">
        <input type="submit" value="<?php echo __( $this->inmueble->activo == 1 ? 'Ocultar' : 'Mostrar' ); ?>" />
        <span><?php echo __('ó <a href="$0">Cancelar</a>', new Url("/admin/inmuebles/$this->codigo")); ?></span>
      </dd>
    </dl>
  </form>
<?php endif; ?>
</div>

<?php echo Controller::dispatch('Admin_Footer'); ?>