<?php echo Controller::dispatch('Admin_Header', array(__('Inmuebles'), $this->codigo, __('Configuración'))); ?>

<div id="breadcrumb">
  <ul>
    <li><a href="<?php echo new Url('/admin/inmuebles'); ?>"><?php echo __('Inmuebles'); ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->codigo"); ?>"><?php echo $this->codigo; ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->codigo/configuracion"); ?>"><?php echo __('Configuración'); ?></a></li>
  </ul>
  <div class="clear"><!-- --></div>
</div>

<div id="content">
<?php if ( !( $this->inmueble->found() ) ) : ?>
  <div class="error">
    <p><?php echo __('Registro <strong>$0</strong> no encontrado.', $this->codigo); ?></p>
  </div>
<?php elseif ( !( $this->paginas ) ) : ?>
  <div class="error">
    <p><?php echo __('El inmueble <strong>$0</strong> no tiene ninguna página. Puede <a href="$1">agregar</a> una.', $this->codigo, new Url("/admin/inmuebles/$this->codigo/paginas/agregar")); ?></p>
  </div>
<?php else : ?>
<?php if ( $this->errors ) : ?>
  <div class="error">
    <p><?php echo __('Por favor verifique los siguientes errores:'); ?></p>
    <ul>
<?php if ( $this->errors['inicio'] ) : ?>
      <li><?php echo __('Página de inicio requerida.'); ?></li>
<?php endif; ?>
<?php if ( $this->errors['diseno'] ) : ?>
      <li><?php echo __('Diseño requerido.'); ?></li>
<?php endif; ?>
    </ul>
  </div>
<?php endif; ?>
  <form action="<?php echo new Url(); ?>" method="post">
    <table cellpadding="0" cellspacing="0">
      <thead>
        <tr>
          <th>#</th>
          <th><?php echo __('Código'); ?></th>
<?php foreach ( $this->idiomas as $idioma ) : ?>
          <th><?php echo __($idioma); ?></th>
<?php endforeach; ?>
          <th>
            <span><?php echo __('Inicio'); ?></span>
            <p><?php echo __('Será la primer página que se visualice al ingresar al micrositio.'); ?></p>
          </th>
          <th>
            <span><?php echo __('Lateral'); ?></span>
            <p><?php echo __('El contenido se mostrará a lo largo de todas las páginas.') ?></p>
          </th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <td>&nbsp;</td>
          <td colspan="<?php echo 1 + sizeof($this->idiomas); ?>">
            <em><?php echo __('Remover'); ?></em>
          </td>
          <td>&nbsp;</td>
          <td>
<?php if ( $this->lateral == 0 ) : ?>
            <input type="radio" class="checkbox" name="lateral" value="0" checked="checked" />
<?php else : ?>
            <input type="radio" class="checkbox" name="lateral" value="0" />
<?php endif; ?>
          </td>
        </tr>
      </tfoot>
      <tbody>
<?php foreach ( $this->paginas as $i => $pagina ) : ?>
        <tr>
          <td><?php echo $i + 1; ?></td>
          <td>
            <a href="<?php echo new Url("/admin/inmuebles/$this->codigo/paginas/$pagina->codigo"); ?>"><?php echo $pagina->codigo; ?></a>
          </td>
<?php foreach ( $this->idiomas as $idioma ) : ?>
<?php if ( isset($pagina->contenidos[$idioma]) ) : ?>
          <td><?php echo $pagina->contenidos[$idioma]->nombre; ?></td>
<?php else : ?>
          <td><em>(<?php echo __('Vacío'); ?>)</em></td>
<?php endif; ?>
<?php endforeach; ?>
          <td>
<?php if ( $this->inicio == $pagina->id ) : ?>
            <input type="radio" class="checkbox" name="inicio" value="<?php echo $pagina->id; ?>" checked="checked" />
<?php else : ?>
            <input type="radio" class="checkbox" name="inicio" value="<?php echo $pagina->id; ?>" />
<?php endif; ?>
          </td>
          <td>
<?php if ( $this->lateral == $pagina->id ) : ?>
            <input type="radio" class="checkbox" name="lateral" value="<?php echo $pagina->id; ?>" checked="checked" />
<?php else : ?>
            <input type="radio" class="checkbox" name="lateral" value="<?php echo $pagina->id; ?>" />
<?php endif; ?>
          </td>
        </tr>
<?php endforeach; ?>
      </tbody>
    </table>
    <dl>
      <dt>
        <label for="diseno"><?php echo __('Diseño'); ?></label>
        <span class="required">*</span>
        <p><?php echo __('Será como se vea el micrositio.'); ?></p>
      </dt>
      <dd>
        <ul class="design">
          <li>
<?php if ( 'default' == $this->diseno ) : ?>
            <input type="radio" name="diseno" value="default" checked="checked" />
<?php else : ?>
            <input type="radio" name="diseno" value="default" />
<?php endif; ?>
            <img src="<?php echo new Url('/stylesheets/default/default.jpg'); ?>" />
          </li>
          <li>
<?php if ( 'garvera' == $this->diseno ) : ?>
            <input type="radio" name="diseno" value="garvera" checked="checked" />
<?php else : ?>
            <input type="radio" name="diseno" value="garvera" />
<?php endif; ?>
            <img src="<?php echo new Url('/stylesheets/garvera/garvera.jpg'); ?>" />
          </li>
          <li>
<?php if ( 'admin' == $this->diseno ) : ?>
            <input type="radio" name="diseno" value="admin" checked="checked" />
<?php else : ?>
            <input type="radio" name="diseno" value="admin" />
<?php endif; ?>
            <img src="<?php echo new Url('/stylesheets/admin/admin.jpg'); ?>" />
          </li>
        </ul>
        <div class="clear"><!-- --></div>
      </dd>

      <dd class="submit">
        <input type="submit" value="<?php echo __('Guardar'); ?>" />
        <span><?php echo __('ó <a href="$0">Cancelar</a>', new Url("/admin/inmuebles/$this->codigo")); ?></span>
      </dd>
    </dl>
  </form>
<?php endif; ?>
</div>

<?php echo Controller::dispatch('Admin_Footer'); ?>