<?php echo Controller::dispatch('Admin_Header', array(__('Inmuebles'), $this->codigo, __('Editar'))); ?>

<div id="breadcrumb">
  <ul>
    <li><a href="<?php echo new Url('/admin/inmuebles'); ?>"><?php echo __('Inmuebles'); ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->codigo"); ?>"><?php echo $this->codigo; ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->codigo/editar"); ?>"><?php echo __('Editar'); ?></a></li>
  </ul>
  <div class="clear"><!-- --></div>
</div>

<div id="content">
<?php if ( !( $this->inmueble->found() ) ) : ?>
  <div class="error">
    <p><?php echo __('Registro <strong>$0</strong> no encontrado.', $this->codigo); ?></p>
  </div>
<?php else : ?>
  <p><?php echo __('Seleccione el idioma que desea editar.'); ?></p>
  <ul>
<?php foreach ( $this->idiomas as $idioma ) : ?>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->codigo/editar/$idioma"); ?>"><?php echo __($idioma); ?></a></li>
<?php endforeach; ?>
  </ul>
<?php endif; ?>
</div>

<?php echo Controller::dispatch('Admin_Footer'); ?>