<?php echo Controller::dispatch('Admin_Header', array(__('Inmuebles'), $this->codigo, __('Fotos'))); ?>

<div id="breadcrumb">
  <ul>
    <li><a href="<?php echo new Url('/admin/inmuebles'); ?>"><?php echo __('Inmuebles'); ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->codigo"); ?>"><?php echo $this->codigo; ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->codigo/fotos"); ?>"><?php echo __('Fotos'); ?></a></li>
  </ul>
  <div class="clear"><!-- --></div>
</div>

<div id="content">
<?php if ( !( $this->inmueble->found() ) ) : ?>
  <div class="error">
    <p><?php echo __('Registro <strong>$0</strong> no encontrado.', $this->codigo); ?></p>
  </div>
<?php else : ?>
<?php if ( Request::hasQuery('deleted') ) : ?>
  <div class="success">
    <p><?php echo __('Foto eliminada con éxito.'); ?></p>
  </div>
<?php endif; ?>
<?php if ( empty($this->fotos) ) : ?>
  <div class="info">
    <p><?php echo __('El inmueble <strong>$0</strong> no tiene ninguna foto. Puede <a href="$1">agregar</a> una.', $this->codigo, new Url("/admin/inmuebles/$this->codigo/fotos/agregar")); ?></p>
  </div>
<?php else : ?>
  <table cellpadding="0" cellspacing="0">
    <thead>
      <tr>
        <th>#</th>
        <th><?php echo __('Foto'); ?></th>
        <th class="actions">&nbsp;</th>
        <th class="actions">
          <a href="<?php echo new Url("/admin/inmuebles/$this->codigo/fotos/agregar") ?>"><?php echo __('Agregar'); ?></a>
        </th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <td colspan="4">
<?php echo Controller::dispatch('Helpers_Pagination', $this->count, $this->page, $this->per); ?>
        </td>
      </tr>
    </tfoot>
    <tbody>
<?php foreach ( $this->fotos as $n => $foto ) : ?>
      <tr>
        <td><?php echo $this->start + $n + 1; ?></td>
        <td><?php echo $foto->codigo; ?></td>
        <td class="actions">
<?php if ( 1 == $foto->posicion ) : ?>
          <span class="disabled"><?php echo __('Subir'); ?></span>
<?php else : ?>
          <a href="<?php echo new Url("/admin/inmuebles/$this->codigo/fotos/$foto->codigo/mover-1"); ?>"><?php echo __('Subir'); ?></a>
<?php endif; ?>
<?php if ( $this->pos == $foto->posicion ) : ?>
          <span class="disabled"><?php echo __('Bajar'); ?></span>
<?php else : ?>
          <a href="<?php echo new Url("/admin/inmuebles/$this->codigo/fotos/$foto->codigo/mover+1"); ?>"><?php echo __('Bajar'); ?></a>
<?php endif; ?>
        </td>
        <td class="actions">
          <a href="<?php echo new Url("/admin/inmuebles/$this->codigo/fotos/$foto->codigo"); ?>"><?php echo __('Ver'); ?></a>
          <a href="<?php echo new Url("/admin/inmuebles/$this->codigo/fotos/$foto->codigo/mover"); ?>"><?php echo __('Mover'); ?></a>
          <a href="<?php echo new Url("/admin/inmuebles/$this->codigo/fotos/$foto->codigo/eliminar"); ?>"><?php echo __('Eliminar'); ?></a>
        </td>
      </tr>
<?php endforeach; ?>
    </tbody>
  </table>
<?php endif; ?>
<?php endif; ?>
</div>

<?php echo Controller::dispatch('Admin_Footer'); ?>