<?php
    echo '<?xml version="1.0" encoding="UTF-8"?>';
    echo "\n";

    $titles = $this->title;
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
    "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" >
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title><?php echo implode(' &laquo; ', array_reverse($this->title)); ?></title>
  <link rel="stylesheet" href="<?php echo new Url('/static/stylesheets/admin.css'); ?>" type="text/css" media="screen" />
</head>
<body>
  <div id="wrapper">
    <div id="header">
      <h1><?php echo array_shift($titles); ?></h1>
<?php if ( sizeof($titles) > 0 ) : ?>
      <p>
<?php foreach ( $titles as $titleURL => $title ) : ?>
        &raquo; <a href="<?php echo new Url($titleURL); ?>"><?php echo $title; ?></a>
<?php endforeach; ?>
      </p>
<?php endif; ?>
    </div>
    <div id="nav">
      <ul>
        <li><a href="<?php echo new Url('/admin'); ?>"><?php echo __('Dashboard'); ?></a></li>
        <li><a href="<?php echo new Url('/admin/categories'); ?>"><?php echo __('Categories'); ?></a></li>
        <li><a href="<?php echo new Url('/admin/businesses'); ?>"><?php echo __('Businesses'); ?></a></li>
        <li><a href="<?php echo new Url('/admin/coupons'); ?>"><?php echo __('Coupons'); ?></a></li>
        <li><a href="<?php echo new Url('/admin/logout'); ?>"><?php echo __('Logout'); ?></a></li>
      </ul>
    </div>
    <div id="content">
