<?php echo Controller::dispatch('Admin_Helpers_Header', array('/admin/categories' => __('Categories'))); ?>

<p><strong>+</strong> <a href="<?php echo new Url('/admin/categories/add'); ?>"><?php echo __('Create a new category'); ?></a></p>

<table cellpadding="0" cellspacing="0">
  <thead>
    <tr>
      <th><?php echo __('Name'); ?></th>
      <th><?php echo __('Status'); ?></th>
      <th><?php echo __('Actions'); ?></th>
    </tr>
  </thead>
<?php if ( $this->count ) : ?>
  <tfoot>
    <tr>
      <td colspan="3">
<?php echo Controller::dispatch('Helpers_Pagination', $this->count, $this->page, $this->per); ?>
      </td>
    </tr>
  </tfoot>
<?php endif; ?>
  <tbody>
<?php if ( $this->categories ) : ?>
<?php foreach ( $this->categories as $i => $category ) : ?>
    <tr class="<?php echo $i % 2 ? 'even' : 'odd'; ?>">
      <td>
        <a href="<?php echo new Url("/admin/categories/$category->id"); ?>"><?php echo $category->name; ?></a>
      </td>
      <td>
<?php if ( $category->active ) : ?>
        <span class="active"><?php echo __('Active'); ?></span>
<?php else : ?>
        <span class="paused"><?php echo __('Paused'); ?></span>
<?php endif; ?>
      </td>
      <td>
        <a href="<?php echo new Url("/admin/categories/$category->id/edit"); ?>"><?php echo __('Edit') ?></a> -
        <a href="<?php echo new Url("/admin/categories/$category->id/delete"); ?>" class="delete"><?php echo __('Delete') ?></a>
      </td>
    </tr>
<?php endforeach; ?>
<?php else : ?>
    <tr>
      <td colspan="3" class="error">
        <p><?php echo __('You haven\'t created any categories yet. Create a category using the link above.'); ?></p>
      </td>
    </tr>
<?php endif; ?>
  </tbody>
</table>

<script type="text/javascript">
//<![CDATA[
var deleteElements = document.getElementsByClassName('delete');
var deleteAction = function( event )
{
    if ( confirm('<?php echo __('Are you sure you want to delete this category?'); ?>') )
    {
        var target = event.target ? event.target : event.currentTarjet;
        var form = document.createElement('form');

        document.body.appendChild(form);

        form.action = target.href;
        form.method = 'post';
        form.submit();
    }

    event.preventDefault();
};

for ( var i = 0, l = deleteElements.length; i < l; i++ )
    deleteElements[i].onclick = deleteAction;
//]]>
</script>

<?php echo Controller::dispatch('Admin_Helpers_Footer'); ?>