<?php echo Controller::dispatch('Admin_Header', array(__('Ayuda'))); ?>

<div id="breadcrumb">
  <ul>
    <li><a href="<?php echo new Url('/admin/ayuda'); ?>"><?php echo __('Ayuda'); ?></a></li>
  </ul>
  <div class="clear"><!-- --></div>
</div>

<div id="content">
  <h1><?php echo __('Ayuda'); ?></h1>
  <ul>
    <li>
      <a href="<?php echo new Url(); ?>#Personas"><?php echo __('Personas'); ?></a>
    </li>
    <li>
      <a href="<?php echo new Url(); ?>#Inmuebles"><?php echo __('Inmuebles'); ?></a>
      <ul>
        <li>
          <a href="<?php echo new Url(); ?>#Inmuebles_Paginas"><?php echo __('Páginas'); ?></a>
        </li>
        <li>
          <a href="<?php echo new Url(); ?>#Inmuebles_Fotos"><?php echo __('Fotos'); ?></a>
        </li>
      </ul>
    </li>
    <li>
      <a href="<?php echo new Url(); ?>#Configuracion"><?php echo __('Configuración'); ?></a>
    </li>
  </ul>

  <h2><a name="Personas"></a><?php echo __('Personas'); ?></h2>

  <h2><a name="Inmuebles"></a><?php echo __('Inmuebles'); ?></h2>

  <h3><a name="Inmuebles_Paginas"></a><?php echo __('Páginas'); ?></h3>
  <p><?php echo __('Vease <a href="$0">Sintaxis Wiki</a>.', new Url('/admin/ayuda/wiki')); ?></p>

  <h3><a name="Inmuebles_Fotos"></a><?php echo __('Fotos'); ?></h3>

  <h2><a name="Configuracion"></a><?php echo __('Configuración'); ?></h2>
  <p><?php echo __('Controla los parámetros básicos del sitio. Estos se almacenan en el archivo <tt>/application.ini</tt>, que nunca debe ser editado a mano y siempre mediante el fomulario de <a href="$0">Configuración</a>.', new Url('/admin/configuracion')); ?></p>
</div>

<?php echo Controller::dispatch('Admin_Footer'); ?>