<?php
    echo '<?xml version="1.0" encoding="UTF-8"?>';
    echo "\n";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
    "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" >
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="robots" content="noindex, nofollow" />
    <title><?php echo $this->title; ?> &raquo; <?php echo __('Panel de Control'); ?> &raquo; <?php echo $this->nombre; ?></title>
    <link rel="shortcut icon" href="<?php echo new Url('/favicon.ico'); ?>" type="image/x-icon" />
    <link rel="stylesheet" href="<?php echo new Url('/stylesheets/reset.css'); ?>" type="text/css" media="all" />
    <link rel="stylesheet" href="<?php echo new Url('/stylesheets/admin/screen.css'); ?>" type="text/css" media="screen" />
  </head>
  <body>
    <div id="wrapper">
      <div id="header">
        <h1 id="logo"><?php echo $this->nombre; ?></h1>
      </div>
      <div id="nav">
        <ul>
          <li class="odd first<?php echo ( 'Principal' == $this->current ) ? ' selected' : ''; ?>">
            <a href="<?php echo new Url('/admin'); ?>"><?php echo __('Principal'); ?></a>
          </li>
          <li class="even<?php echo ( 'Personas' == $this->parent ) ? ' selected' : ''; ?>">
            <a href="<?php echo new Url('/admin/personas'); ?>"><?php echo __('Personas'); ?></a>
          </li>
          <li class="odd<?php echo ( 'Inmuebles' == $this->parent ) ? ' selected' : ''; ?>">
            <a href="<?php echo new Url('/admin/inmuebles'); ?>"><?php echo __('Inmuebles'); ?></a>
          </li>
          <li class="even<?php echo ( 'Configuracion' == $this->current ) ? ' selected' : ''; ?>">
            <a href="<?php echo new Url('/admin/configuracion'); ?>"><?php echo __('Configuración'); ?></a>
          </li>
          <li class="odd last"><a href="<?php echo new Url('/admin/salir'); ?>"><?php echo __('Salir'); ?></a></li>
        </ul>
        <div class="clear"><!-- --></div>
      </div>
<?php echo Controller::dispatch('Helpers_Idiomas'); ?>
