<?php echo Controller::dispatch('Admin_Header', array(__('Principal'))); ?>

<div id="breadcrumb">
  <ul>
    <li><a href="<?php echo new Url('/admin'); ?>"><?php echo __('Principal'); ?></a></li>
  </ul>
  <div class="clear"><!-- --></div>
</div>

<div id="content">
  <h2><?php echo $this->nombre; ?></h2>
  <ul class="dashboard">
    <li>
      <a href="<?php echo new Url('/admin/personas') ?>"><?php echo __('Personas'); ?></a>
      <p><?php echo __('Personas que tienen acceso al Panel de Control.') ?></p>
    </li>
    <li>
      <a href="<?php echo new Url('/admin/inmuebles') ?>"><?php echo __('Inmuebles'); ?></a>
      <p><?php echo __('Micrositios con información sobre las propiedades.') ?></p>
    </li>
    <li>
      <a href="<?php echo new Url('/admin/configuracion') ?>"><?php echo __('Configuración'); ?></a>
      <p><?php echo __('Parámetros básicos.') ?></p>
    </li>
  </ul>
</div>

<?php echo Controller::dispatch('Admin_Footer'); ?>