<?php echo Controller::dispatch('Admin_Header', array(__('Personas'), $this->usuario, __('Editar'))); ?>

<div id="breadcrumb">
  <ul>
    <li><a href="<?php echo new Url('/admin/personas'); ?>"><?php echo __('Personas'); ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/personas/$this->usuario"); ?>"><?php echo $this->usuario; ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/personas/$this->usuario/editar"); ?>"><?php echo __('Editar'); ?></a></li>
  </ul>
  <div class="clear"><!-- --></div>
</div>

<div id="content">
<?php if ( !( $this->persona->found() ) ) : ?>
  <div class="error">
    <p><?php echo __('Registro <strong>$0</strong> no encontrado.', $this->usuario); ?></p>
  </div>
<?php else : ?>
  <form action="<?php echo new Url(); ?>" method="post">
    <dl>
      <dt><?php echo __('Usuario'); ?></dt>
      <dd><?php echo $this->usuario; ?></dd>

      <dt><?php echo __('Contraseña'); ?></dt>
      <dd><?php echo __('Haga clic <a href="$0">aquí</a> para editar la contraseña.', new Url("/admin/personas/$this->usuario/editar/contrasena")); ?></dd>

      <dt><label for="nombre"><?php echo __('Nombre y Apellidos'); ?></label></dt>
      <dd>
        <input type="text" name="nombre" id="nombre" value="<?php echo $this->nombre; ?>" />
      </dd>

      <dd class="submit">
        <input type="submit" class="add" value="<?php echo __('Editar'); ?>" />
        <span><?php echo __('ó <a href="$0">Cancelar</a>', new Url("/admin/personas/$this->usuario")); ?></span>
      </dd>
    </dl>
  </form>
<?php endif; ?>
</div>

<?php echo Controller::dispatch('Admin_Footer'); ?>