<?php echo Controller::dispatch('Admin_Header', array(__('Personas'), $this->usuario, __('Eliminar'))); ?>

<div id="breadcrumb">
  <ul>
    <li><a href="<?php echo new Url('/admin/personas'); ?>"><?php echo __('Personas'); ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/personas/$this->usuario"); ?>"><?php echo $this->usuario; ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/personas/$this->usuario/eliminar"); ?>"><?php echo __('Eliminar'); ?></a></li>
  </ul>
  <div class="clear"><!-- --></div>
</div>

<div id="content">
<?php if ( !( $this->persona->found() ) ) : ?>
  <div class="error">
    <p><?php echo __('Registro <strong>$0</strong> no encontrado.', $this->usuario); ?></p>
  </div>
<?php else : ?>
  <div class="warning">
    <p><?php echo __('Se encuentra a punto de eliminar a <strong>$0</strong> del sistema. ¿Desea continuar?', $this->persona->nombre); ?></p>
  </div>
  <form action="<?php echo new Url(); ?>" method="post">
    <dl>
      <dd class="submit">
        <input type="submit" value="<?php echo __('Eliminar'); ?>" />
        <span><?php echo __('ó <a href="$0">Cancelar</a>', new Url("/admin/personas/$this->usuario")); ?></span>
      </dd>
    </dl>
  </form>
<?php endif; ?>
</div>

<?php echo Controller::dispatch('Admin_Footer'); ?>