<p class="pagination">
<?php if ( $this->page == 1 && $this->pages > 1 ) : ?>
    <span class="current">1</span>
<?php elseif ( $this->pages > 1 ) : ?>
    <a href="<?php echo new Url(array('page' => 1)); ?>">1</a>
<?php endif; ?>
<?php if ( $this->pages > 5 ) : ?>
<?php $countStart = min( max( 1, $this->page - 4 ), $this->pages - 5 ); ?>
<?php $countEnd = max( min( $this->pages, $this->page + 4 ), 6 ); ?>
<?php if ( $countStart > 1 ) : ?>
    <span> ... </span>
<?php endif; ?>
<?php for ( $i = $countStart + 1; $i < $countEnd; $i++ ) : ?>
<?php if ( $i == $this->page ) : ?>
    <span class="current"><?php echo $i; ?></span>
<?php else : ?>
    <a href="<?php echo new Url(array('page' => $i)); ?>"><?php echo $i; ?></a>
<?php endif; ?>
<?php endfor; ?>
<?php if ( $countEnd < $this->pages ) : ?>
    <span> ... </span>
<?php endif; ?>
<?php else : ?>
<?php for ( $i = 2; $i < $this->pages; $i++ ) : ?>
<?php if ( $i == $this->page ) : ?>
    <span class="current"><?php echo $i; ?></span>
<?php else : ?>
    <a href="<?php echo new Url(array('page' => $i)); ?>"><?php echo $i; ?></a>
<?php endif; ?>
<?php endfor; ?>
<?php endif; ?>
<?php if ( $this->pages == $this->page ) : ?>
    <span class="current"><?php echo $this->pages; ?></span>
<?php else : ?>
    <a href="<?php echo new Url(array('page' => $this->pages)); ?>"><?php echo $this->pages; ?></a>
<?php endif; ?>
</p>
