<?php
    echo '<?xml version="1.0" encoding="UTF-8"?>';
    echo "\n";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
    "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" >
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title><?php echo implode(' &laquo; ', array_reverse($this->title)); ?></title>
</head>
<body>
  <div id="wrapper">
