<?php echo Controller::dispatch('Admin_Header', array(__('Inmuebles'), $this->inmuebleCodigo, __('Fotos'), $this->fotoCodigo, __('Mover'))); ?>

<div id="breadcrumb">
  <ul>
    <li><a href="<?php echo new Url('/admin/inmuebles'); ?>"><?php echo __('Inmuebles'); ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->inmuebleCodigo"); ?>"><?php echo $this->inmuebleCodigo; ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->inmuebleCodigo/fotos"); ?>"><?php echo __('Fotos'); ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->inmuebleCodigo/fotos/$this->fotoCodigo"); ?>"><?php echo $this->fotoCodigo; ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/inmuebles/$this->inmuebleCodigo/fotos/$this->fotoCodigo/mover$this->signo$this->cantidad"); ?>"><?php echo __('Mover'); ?></a></li>
  </ul>
  <div class="clear"><!-- --></div>
</div>

<div id="content">
<?php if ( !( $this->inmueble->found() ) ) : ?>
  <div class="error">
    <p><?php echo __('Registro <strong>$0</strong> no encontrado.', $this->inmuebleCodigo); ?></p>
  </div>
<?php elseif ( !( $this->foto->found() ) ) : ?>
  <div class="error">
    <p><?php echo __('Registro <strong>$0</strong> no encontrado.', $this->fotoCodigo); ?></p>
  </div>
<?php elseif ( false === $this->new ) : ?>
  <div class="error">
    <p><?php echo __('La fotografía no puede ser movida.'); ?></p>
  </div>
<?php else : ?>
  <div class="warning">
<?php switch ( $this->signo ) : ?>
<?php case '+': ?>
<?php if ( 1 == $this->cantidad ) : ?>
    <p><?php echo __('Se encuentra a punto de desplazar <strong>$0</strong> un lugar hacia abajo. ¿Desea continuar?', $this->fotoCodigo); ?></p>
<?php else : ?>
    <p><?php echo __('Se encuentra a punto de desplazar <strong>$0</strong> $1 lugares hacia abajo. ¿Desea continuar?', $this->fotoCodigo, $this->cantidad); ?></p>
<?php endif; ?>
<?php break; ?>
<?php case '-': ?>
<?php if ( 1 == $this->cantidad ) : ?>
    <p><?php echo __('Se encuentra a punto de desplazar <strong>$0</strong> un lugar hacia arriba. ¿Desea continuar?', $this->fotoCodigo); ?></p>
<?php else : ?>
    <p><?php echo __('Se encuentra a punto de desplazar <strong>$0</strong> $1 lugares hacia arriba. ¿Desea continuar?', $this->fotoCodigo, $this->cantidad); ?></p>
<?php endif; ?>
<?php break; ?>
<?php endswitch; ?>
  </div>
  <form action="<?php echo new Url(); ?>" method="post">
    <dl>
      <dd class="submit">
        <input type="submit" value="<?php echo __('Mover'); ?>" />
        <span><?php echo __('ó <a href="$0">Cancelar</a>', new Url("/admin/inmuebles/$this->inmuebleCodigo/fotos/$this->fotoCodigo")); ?></span>
      </dd>
    </dl>
  </form>
<?php endif; ?>
</div>

<?php echo Controller::dispatch('Admin_Footer'); ?>