<?php echo Controller::dispatch('Admin_Header', array(__('Configuración'), __($this->idioma))); ?>

<div id="breadcrumb">
  <ul>
    <li><a href="<?php echo new Url('/admin/configuracion'); ?>"><?php echo __('Configuración'); ?></a></li>
    <li>&raquo;</li>
    <li><a href="<?php echo new Url("/admin/configuracion/$this->idioma"); ?>"><?php echo __($this->idioma); ?></a></li>
  </ul>
  <div class="clear"><!-- --></div>
</div>
<div id="content">
<?php if ( Request::hasQuery('edited') ) : ?>
  <div class="success">
    <p><?php echo __('Configuración editada con éxito.'); ?></p>
  </div>
<?php endif; ?>
<?php if ( Request::hasQuery('error') ) : ?>
  <div class="success">
    <p><?php echo __('Ocurrió un error al guardar la Configuración.'); ?></p>
  </div>
<?php endif; ?>
  <form action="<?php echo new Url(); ?>" method="post">
    <dl>
      <dt>
        <label for="title"><?php echo __('Título'); ?></label>
      </dt>
      <dd>
        <input type="text" class="large" name="title" id="title" value="<?php echo $this->title; ?>" maxlength="255" />
        <p><?php echo __('El título de la página principal.'); ?></p>
      </dd>

      <dt>
        <label for="keywords"><?php echo __('Palabras claves'); ?></label>
      </dt>
      <dd>
        <input type="text" class="large" name="keywords" id="keywords" value="<?php echo $this->keywords; ?>" maxlength="255" />
        <p><?php echo __('Separadas por comas. Ej: Apartments, Flats, Buenos Aires, Rent'); ?></p>
      </dd>

      <dt>
        <label for="description"><?php echo __('Descripción'); ?></label>
      </dt>
      <dd>
        <input type="text" class="large" name="description" id="description" value="<?php echo $this->description; ?>" maxlength="255" />
        <p><?php echo __('Una descripción general del sitio. Normalmente utilizada por los buscadores para posicionar.'); ?></p>
      </dd>

      <dd class="submit">
        <input type="submit" value="<?php echo __('Guardar'); ?>" />
        <span><?php echo __('ó <a href="$0">Cancelar</a>', new Url('/admin/configuracion')); ?></span>
      </dd>
    </dl>
  </form>
</div>

<?php echo Controller::dispatch('Admin_Footer'); ?>