<?php
    echo '<?xml version="1.0" encoding="UTF-8"?>';
    echo "\n";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
    "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" >
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title><?php echo $this->title; ?> &raquo; <?php echo $this->inmueble->titulo; ?> &laquo; <?php echo $this->nombre; ?></title>
    <link rel="shortcut icon" href="<?php echo new Url('/favicon.ico'); ?>" type="image/x-icon" />
    <link rel="stylesheet" href="<?php echo new Url('/stylesheets/reset.css'); ?>" type="text/css" media="all" />
    <link rel="stylesheet" href="<?php echo new Url("/stylesheets/{$this->inmueble->diseno}/screen.css"); ?>" type="text/css" media="screen" />
  </head>
  <body>
    <div id="wrapper">
      <div id="header">
        <div class="inner">
<?php echo Controller::dispatch('Helpers_Idiomas'); ?>
          <h2 id="logo">
            <a href="<?php echo new Url("/{$this->inmueble->url}"); ?>"><span><?php echo $this->inmueble->nombre; ?></span></a>
          </h2>
        </div>
      </div>
      <div id="nav">
        <div class="inner">
          <ul>
<?php foreach ( $this->paginas as $i => $pagina ) : ?>
            <li class="<?php echo $i % 2 == 0 ? 'odd' : 'even'; ?><?php echo 0 == $i ? ' first' : ''; ?><?php echo $this->paginasCount - 1 == $i ? ' last' : ''; ?><?php echo $pagina->id == $this->pagina->id ? ' selected' : ''; ?>">
              <a href="<?php echo new Url("/{$this->inmueble->url}/$pagina->url"); ?>"><?php echo $pagina->nombre; ?></a>
            </li>
<?php endforeach; ?>
          </ul>
          <div class="clear"><!-- --></div>
        </div>
      </div>
<?php if ( $this->sidebar ) : ?>
      <div id="sidebar">
        <div class="inner">
<?php echo Controller::dispatch('Inmueble_Pagina_Pagina', $this->inmueble, $this->sidebar); ?>
        </div>
      </div>
<?php endif; ?>
      <div id="content">
        <div class="inner">
